/**
 * Cấu hình Tailwind cho VIMC People.
 * Chuyển từ cấu hình inline (CDN) trong index.html sang build PostCSS chuẩn production.
 * Giữ NGUYÊN toàn bộ token màu / spacing / typography cũ để không vỡ giao diện.
 */
import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f6fbf4',
        'on-primary-fixed-variant': '#00522f',
        'outline-variant': '#bec9bf',
        'surface-container': '#ebefe9',
        'secondary-fixed': '#ffdbd1',
        'on-primary-container': '#aeffca',
        'secondary-fixed-dim': '#ffb5a0',
        'on-secondary-container': '#681800',
        'tertiary-fixed-dim': '#ffb2b7',
        'on-surface': '#181d19',
        'on-tertiary-fixed': '#40010e',
        'background-cream': '#F7F4EC',
        'primary-container': '#1f7a4d',
        'inverse-surface': '#2d322d',
        background: '#f6fbf4',
        'inverse-primary': '#82d8a3',
        'charcoal-ink': '#14201A',
        'teal-herb': '#1B7E7A',
        'tertiary-container': '#a85059',
        'on-secondary-fixed': '#3b0900',
        'on-surface-variant': '#3f4941',
        'on-primary-fixed': '#002110',
        'surface-dim': '#d7dbd5',
        'inverse-on-surface': '#eef2eb',
        'on-background': '#181d19',
        'accent-green': '#2FAE5E',
        'secondary-container': '#ff734a',
        'on-error': '#ffffff',
        'primary-fixed': '#9ef5be',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        'alert-fire': '#E0312A',
        'tertiary-fixed': '#ffdadb',
        'bronze-gold': '#C6952B',
        'on-tertiary-fixed-variant': '#7a2c36',
        'on-error-container': '#93000a',
        secondary: '#aa3610',
        primary: '#006038',
        'surface-container-low': '#f1f5ee',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffe8e8',
        'surface-container-high': '#e5e9e3',
        'surface-tint': '#066c41',
        'surface-variant': '#dfe4dd',
        'surface-container-highest': '#dfe4dd',
        'primary-fixed-dim': '#82d8a3',
        'on-primary': '#ffffff',
        tertiary: '#8a3942',
        'on-secondary-fixed-variant': '#862200',
        outline: '#6f7a71',
        surface: '#f6fbf4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-gap': '16px',
        gutter: '16px',
        'inline-gap': '12px',
        'card-padding': '24px',
        'container-margin': '20px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Be Vietnam Pro'],
        'display-lg': ['Be Vietnam Pro'],
        'headline-md': ['Be Vietnam Pro'],
        'title-lg': ['Be Vietnam Pro'],
        'body-md': ['Be Vietnam Pro'],
        'label-md': ['Be Vietnam Pro'],
        'headline-lg': ['Be Vietnam Pro'],
        'label-lg': ['Be Vietnam Pro'],
        'body-lg': ['Be Vietnam Pro'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
